server:
  port: 8081

opalinfo:
    tripleStore:
      url: http://${OPAL_TRIPLESTORE_URL}:3030/opal/query
      username: ${OPAL_TRIPLESTORE_USERNAME}
      password: ${OPAL_TRIPLESTORE_PASSWORD}

management.health.elasticsearch.enabled: false