server:
  port: 8081

info:
  opal:
    tripleStore:
      url: http://${OPAL_TRIPLESTORE_URL}:3030/mcloud/query
      username: ${OPAL_TRIPLESTORE_USERNAME}
      password: ${OPAL_TRIPLESTORE_PASSWORD}

management.health.elasticsearch.enabled: false